env:
  browser: true
  es2020: true

extends:
  - airbnb
  - prettier

parserOptions:
  ecmaVersion: latest
  sourceType: module

settings:
  react:
    version: detect

plugins:
  - import
  - jsx-a11y
  - react
  - react-hooks
  - react-refresh
  - simple-import-sort

rules:
  import/extensions: off
  import/no-absolute-path: off
  no-shadow: off
  react/react-in-jsx-scope: off
  simple-import-sort/imports: error
  simple-import-sort/exports: error
